// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_y9YVRrPtp",
    "aws_user_pools_web_client_id": "3pqv48rc2rn8kdlhpajdtb0h9u",
    "aws_content_delivery_bucket": "ggamplifynggql-20181110162856--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d1l62ffnn2clel.cloudfront.net"
};


export default awsmobile;
